name: Release

on: { push: { tags: '[0-9]+.[0-9]+.[0-9]+*' } }

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: { contents: write, id-token: write, attestations: write }
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2

      - run: bun i
      - run: bun typecheck
      - run: bun lint
      - run: bun prod

      - uses: actions/attest@v4
        with:
          subject-path: manifest.json, main.js, styles.css
      - run: gh release create $TAG --title $TAG --draft manifest.json main.js styles.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}